/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AButtonGroup: typeof import('@arco-design/web-vue')['ButtonGroup']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ASpin: (typeof import('@arco-design/web-vue'))['Spin']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    AUpload: typeof import('@arco-design/web-vue')['Upload']
    FlowDesigner: typeof import('./src/components/FlowDesigner/FlowDesigner.vue')['default']
    FromRenderer: typeof import('./src/components/FromRenderer/FromRenderer.vue')['default']
    HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
    IconCommunity: (typeof import('./src/components/icons/IconCommunity.vue'))['default']
    IconDocumentation: (typeof import('./src/components/icons/IconDocumentation.vue'))['default']
    IconEcosystem: (typeof import('./src/components/icons/IconEcosystem.vue'))['default']
    IconSupport: (typeof import('./src/components/icons/IconSupport.vue'))['default']
    IconTooling: (typeof import('./src/components/icons/IconTooling.vue'))['default']
    Node: typeof import('./src/components/Node/Node.vue')['default']
    NodeRenderer: (typeof import('./src/components/Node/NodeRenderer.vue'))['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: (typeof import('./src/components/TheWelcome.vue'))['default']
    WelcomeItem: (typeof import('./src/components/WelcomeItem.vue'))['default']
  }
}
