/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AButtonGroup: typeof import('@arco-design/web-vue')['ButtonGroup']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    AUpload: typeof import('@arco-design/web-vue')['Upload']
    FlowDesigner: typeof import('./src/components/FlowDesigner/FlowDesigner.vue')['default']
    FromRenderer: typeof import('./src/components/FromRenderer/FromRenderer.vue')['default']
    Node: typeof import('./src/components/Node/Node.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
