server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    context-path: /api
  port: 8096
spring:
  application:
    name: autoflow
  jackson:
    serialization:
      write-null-map-values: true
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:100MB}
      max-request-size: ${MAX_REQUEST_SIZE:200MB}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/ola?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DATASOURCE_NAME:root}
    password: ${DATASOURCE_PASSWORD:123456}
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always

logging:
  level:
    io.autoflow.*: debug


