server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    context-path: /api
  port: 8096
spring:
  application:
    name: autoflow
  jackson:
    serialization:
      write-null-map-values: true
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:100MB}
      max-request-size: ${MAX_REQUEST_SIZE:200MB}
  datasource:
    url: jdbc:postgresql://localhost:5432/autoflow
    username: postgres
    password: 123456
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
  dynamic:
    tp:
      executors:
        - threadPoolName: workflow_thread_pool
          executorType: eager
          corePoolSize: 10
          maximumPoolSize: 20
          queueCapacity: 2000
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
ola:
  crud:
    default-db-type: postgresql
  security:
    authenticate-endpoint: "/login"
    excluded-uris:
      - "/**"

dromara:
  x-file-storage:
    local-plus:
      - platform: local-plus # 存储平台标识
        enable-storage: true
        storage-path: ${FILE_STORAGE_PATH:/Users/yiumankam/Desktop/autoflow_upload/}
    default-platform: local-plus
logging:
  level:
    io.autoflow.*: debug


