server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    context-path: /api
  port: 8096
spring:
  application:
    name: autoflow
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:100MB}
      max-request-size: ${MAX_REQUEST_SIZE:200MB}
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DATASOURCE_URL:jdbc:h2:file:~/.h2/test}
    username: root
    password:
#mybatis-plus相关
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


