server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    context-path: /api
  port: 8096
spring:
  application:
    name: autoflow
  jackson:
    serialization:
      write-null-map-values: true
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:100MB}
      max-request-size: ${MAX_REQUEST_SIZE:200MB}
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DATASOURCE_URL:jdbc:h2:mem:test;mode=LEGACY;NON_KEYWORDS=USER}
    username: root
    password:
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
flowable:
  async-executor-activate: false
  history-level: none
  idm:
    enabled: false

logging:
  level:
    io.autoflow.*: debug
    org.flowable.*: debug


