server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    context-path: /api
  port: 8096
spring:
  application:
    name: autoflow
  jackson:
    serialization:
      write-null-map-values: true
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:100MB}
      max-request-size: ${MAX_REQUEST_SIZE:200MB}
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
ola:
  crud:
    default-db-type: mongodb
  security:
    authenticate-endpoint: "/login"
    excluded-uris:
      - "/**"
logging:
  level:
    io.autoflow.*: debug


